main:
  - name: Posts
    url: /posts/
    weight: 1
  - name: Notes
    url: /notes/
    weight: 2
  - identifier: about
    name: About
    url: /posts/about-me
    weight: 10
  # - identifier: archives
  #   name: Archives 
  #   url: /archives/
  #   weight: 20
  # - identifier: categories
  #   name: Categories
  #   url: /categories/
  #   weight: 30
  # - identifier: tags
  #   name: Tags
  #   url: /tags/
  #   weight: 40
  # - identifier: example
  #   name: example.org
  #   url: https://example.org
  #   weight: 50